[package]
name = "file_reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10"
hex = "0.4"
rand = "0.8"
aes = "0.7"
generic-array = "0.14"
typenum = "1.13"